[package]
name = "aoc_macro"
version = "0.1.0"
authors = ["Anton Österberg <anton@42x.io>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
regex = "1.3"
syn = { version = "1.0", features = ["parsing"] }
quote = "1.0"
lazy_static = "1.4"