#!/bin/bash

day=$1
f=$day"a.py"
if [ -f $f ]
then
  echo 'file already exists'
else
  sed "s/£/$day/g" template.py > $f
  source cookie.txt
  curl "https://adventofcode.com/2020/day/${day}/input" -H "$cookie" --compressed > $day.txt
  firefox "https://adventofcode.com/2020/day/$day"
fi
